# -*- coding: utf-8 -*-
"""mychatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0b5u-UFV3tYCqE1RMgBIjmL-64Aud_O
"""

import os
import nltk
import ssl #Python ssl module provides functions and classes to use Secure Sockets Layer (SSL) and Transport Layer Security (TLS) to secure communication both server and client side.
import streamlit as st #lib specific for ml
import random #python module used to genrate random numbers
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

ssl._create_defalut_https_context = ssl._create_unverified_context
nltk.data.path.append(os.path.abspath("nltk_data"))
nltk.download('punkt')

#!pip install streamlit

intents=[
    {
        "tag": "greetings",
        "patterns": ["hi","hello","hey","how are you?","whats up"],
        "responses":["hi there","hello","hey","i am fine","thank you"],

    },
    {
        "tag":"goodbye",
        "patterns": ["bye","seeya later","goodbye","take care"],
        "responses":["goodbye", "seeya later", "bye","you too"]
    },
    {
        "tag":"thanks",
        "patterns": ["thank you","Thanks","Thanks a lot","I appreciate"],
        "responses":[" You are welcome","No problem"," Glad i could help"]
    },
    {
        "tag": "about",
        "patterns": ["What can you do","Who are you", "what are you","what is your purpose"],
        "responses":["I am chatbot", "My purpose is to assist you","i can answer your questions"]

    },
    {"tag": "help",
        "patterns": ["Help", "I need help", "Can you help me", "What should I do"],
        "responses": ["Sure, what do you need help with?", "I'm here to help. What's the problem?", "How can I assist you?"]
    },
    {
        "tag": "age",
        "patterns": ["How old are you", "What's your age"],
        "responses": ["I don't have an age. I'm a chatbot.", "I was just born in the digital world.", "Age is just a number for me."]
    },
    {
        "tag": "weather",
        "patterns": ["What's the weather like", "How's the weather today"],
        "responses": ["I'm sorry, I cannot provide real-time weather information.", "You can check the weather on a weather app or website."]
    },
    {
        "tag": "budget",
        "patterns": ["How can I make a budget", "What's a good budgeting strategy", "How do I create a budget"],
        "responses": ["To make a budget, start by tracking your income and expenses. Then, allocate your income towards essential expenses like rent, food, and bills. Next, allocate some of your income towards savings and debt repayment. Finally, allocate the remainder of your income towards discretionary expenses like entertainment and hobbies.", "A good budgeting strategy is to use the 50/30/20 rule. This means allocating 50% of your income towards essential expenses, 30% towards discretionary expenses, and 20% towards savings and debt repayment.", "To create a budget, start by setting financial goals for yourself. Then, track your income and expenses for a few months to get a sense of where your money is going. Next, create a budget by allocating your income towards essential expenses, savings and debt repayment, and discretionary expenses."]
    },
    {
        "tag": "credit_score",
        "patterns": ["What is a credit score", "How do I check my credit score", "How can I improve my credit score"],
        "responses": ["A credit score is a number that represents your creditworthiness. It is based on your credit history and is used by lenders to determine whether or not to lend you money. The higher your credit score, the more likely you are to be approved for credit.", "You can check your credit score for free on several websites such as Credit Karma and Credit Sesame."]
    }
]

vectorizer= TfidfVectorizer()
LR=LogisticRegression(random_state=0, max_iter= 1000)

tags=[]
patterns=[]
for intent in intents:
  for pattern in intent['patterns']:
    tags.append(intent['tag'])
    patterns.append(pattern)

x= vectorizer.fit_transform(patterns)
y= tags
LR.fit(x,y)

def chatbot(input_text):
  input_text= vectorizer.transform([input_text])
  tag= LR.predict(input_text)[0]
  for intent in intents:
    if intent['tag']== tag:
      response= random.choice(intent['responses'])
      return response

counter =0

def main():
  global counter
  st.title("Chatbot")
  st.write("welcome to chatbot. please type message and press enter.")

  counter +=1
  user_input =st.text_input("You:", key=f"user_input_{counter}")

  if user_input:
    response= chatbot(user_input)
    st.text_area("Chatbot:", value= response, height=100, max_chars= None, key= f"chatbot_response_{counter}")

    if response.lower() in ['goodbye', 'bye']:
      st.write("thank you. bye")
      st.stop()

if  __name__== '__main__':
    main()































